import express from 'express';
import Path from 'path';
import { fileURLToPath } from 'url';
import session from 'express-session';
import pkg from './package.json' with { type: 'json' };
import globalMiddleware from './src/middleware/global.js';
import routes from './src/routes/router.js';
import { loadSessionUser } from './src/middleware/auth.js';
import swaggerUi from 'swagger-ui-express';
import swaggerDocument from './swagger.json' with { type: 'json' };

const __filename = fileURLToPath(import.meta.url);
const __dirname = Path.dirname(__filename);

const app = express();

// Add version info to res.locals for access in templates.
app.use((req, res, next) => {
    res.locals.appVersion = pkg.version;
    next();
});

// Configure static files and EJS templates.
app.use(express.static(Path.join(__dirname, 'public')));
app.set('view engine', 'ejs');
app.set('views', Path.join(__dirname, 'src/views'));

// Parse JSON and URL-encoded request bodies.
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true, limit: '10mb' }));

app.use(globalMiddleware);

// Set up session management. Must be registered before any route or middleware that uses the session.
// In production and local development the real secret is provided by the SESSION_SECRET
// environment variable (local .env / Render). The fallback below only keeps the app bootable
// in contexts with no secret configured (e.g. a fresh test run) — it is not a real secret.
const sessionSecret = process.env.SESSION_SECRET || 'kizuna-rail-insecure-dev-fallback-change-me';

app.use(session({
    secret: sessionSecret,
    resave: false,
    saveUninitialized: false,
    rolling: true,
    cookie: { maxAge: 60 * 60 * 1000 } // Session expires after 1 hour of inactivity
}));

// Copy the session user to req.user / res.locals.user for routes and EJS templates.
app.use(loadSessionUser);

app.use('/', routes);

// Serve the interactive Swagger UI for the JSON API (generated by `npm run swagger`).
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));

// Catch requests that did not match a route.
app.use((req, res, next) => {
    const err = new Error('Page Not Found');
    err.status = 404;
    next(err);
});

// Render the appropriate error page.
app.use((err, req, res, next) => {
    const status = err.status || 500;
    const template = status === 404 ? '404' : '500';
    const context = {
        title: status === 404 ? 'Page Not Found' : 'Server Error',
        error: err.message,
        stack: err.stack
    };

    return res.status(status).render(`errors/${template}`, context);
});

export default app;
